#!/usr/bin/env bash
# Process using ctrl+c in the previous task

k=$(pgrep -f "4-to_infinity_and_beyond" | grep -v $$ | head -n 1 | awk 'NR==1{print $1}')

if [ -n "$k" ]
then
	echo "Stopping 4-to_infinity_and_beyond process with PID $k"
	kill "$k"
else
	echo "4-to_infinity_and_beyond process not found"
fi
