#!/usr/bin/env bash
# School file's informations

my_file="school"

if [ -e "$my_file" ]
then
    echo "school file exists"
    
    if [ -s "$my_file" ]
    then
        echo "school file is not empty"
    else
        echo "school file is empty"
    fi
    
    if [ -f "$my_file" ]
    then
        echo "school is a regular file"
    fi
else
    echo "school file does not exist"
fi
